from pathlib import Path
import PySimpleGUI as sg
from docxtpl import DocxTemplate

document_path = Path(__file__).parent / "template.docx"
doc = DocxTemplate(document_path)

values = {
    "subject": 'محمد',
    'providedTraininGroup': 'محمد',
    'category': 'محمد',
    'prerequisite': 'محمد',
    'field': 'محمد',
    'courseLocation': 'محمد',
    'courseTime': 'محمد',
    'inchargeName': 'محمد',
    'incharge': 'محمد',
    'inchargeField': 'محمد',
    'officeLocation': 'محمد',
    'inchargePhone': 'محمد',
    'inchargeEmail': 'محمد',
    'teacherName': 'محمد',
    'teacherRank': 'محمد',
    'teacherField': 'محمد',
    'teacherEmail': 'محمد',
    'teacherLocation': 'محمد',
    'teacherPhone': 'محمد',
    'lastUpdate': 'محمد',
    'subjectDescription': 'محمد',
    'purpose1': 'محمد',
    'sp1': 'محمد',
    'do1': 'محمد',
    'k1': 'محمد',
    'a1': 'محمد',
    's1': 'محمد',
    'ea1': 'محمد',
    'tm1': 'محمد',
    'lm1': 'محمد',
    'et1': 'محمد',
    'em1': 'محمد',
    't1': 'محمد',
    'purpose1': 'محمد',
    'sp1': 'محمد',
    'do1': 'محمد',
    'k1': 'محمد',
    'a1': 'محمد',
    's1': 'محمد',
    'ea1': 'محمد',
    'tm1': 'محمد',
    'lm1': 'محمد',
    'et1': 'محمد',
    'em1': 'محمد',
    't1': 'محمد',
    'purpose2': 'محمد',
    'sp2': 'محمد',
    'do2': 'محمد',
    'k2': 'محمد',
    'a2': 'محمد',
    's2': 'محمد',
    'ea2': 'محمد',
    'tm2': 'محمد',
    'lm2': 'محمد',
    'et2': 'محمد',
    'em2': 'محمد',
    't2': 'محمد',
    'purpose3': 'محمد',
    'sp3': 'محمد',
    'do3': 'محمد',
    'k3': 'محمد',
    'a3': 'محمد',
    's3': 'محمد',
    'ea3': 'محمد',
    'tm3': 'محمد',
    'lm3': 'محمد',
    'et3': 'محمد',
    'em3': 'محمد',
    't3': 'محمد',
    'purpose4': 'محمد',
    'sp4': 'محمد',
    'do4': 'محمد',
    'k4': 'محمد',
    'a4': 'محمد',
    's4': 'محمد',
    'ea4': 'محمد',
    'tm4': 'محمد',
    'lm4': 'محمد',
    'et4': 'محمد',
    'em4': 'محمد',
    't4': 'محمد',
    'purpose5': 'محمد',
    'sp5': 'محمد',
    'do5': 'محمد',
    'k5': 'محمد',
    'a5': 'محمد',
    's5': 'محمد',
    'ea5': 'محمد',
    'tm5': 'محمد',
    'lm5': 'محمد',
    'et5': 'محمد',
    'em5': 'محمد',
    't5': 'محمد',
    'purpose6': 'محمد',
    'sp6': 'محمد',
    'do6': 'محمد',
    'k6': 'محمد',
    'a6': 'محمد',
    's6': 'محمد',
    'ea6': 'محمد',
    'tm6': 'محمد',
    'lm6': 'محمد',
    'et6': 'محمد',
    'em6': 'محمد',
    't6': 'محمد',
    'purpose7': 'محمد',
    'sp7': 'محمد',
    'do7': 'محمد',
    'k7': 'محمد',
    'a7': 'محمد',
    's7': 'محمد',
    'ea7': 'محمد',
    'tm7': 'محمد',
    'lm7': 'محمد',
    'et7': 'محمد',
    'em7': 'محمد',
    't7': 'محمد',
    'purpose8': 'محمد',
    'sp8': 'محمد',
    'do8': 'محمد',
    'k8': 'محمد',
    'a8': 'محمد',
    's8': 'محمد',
    'ea8': 'محمد',
    'tm8': 'محمد',
    'lm8': 'محمد',
    'et8': 'محمد',
    'em8': 'محمد',
    't8': 'محمد',
}

layout = [
    [sg.Text("گروه آموزشی ارائه دهنده:", justification="right"), sg.Input(key="providerTrainingGroup", do_not_clear=False, justification='right', font=('B Nazanin', 12))],
    [sg.Text("subject:"), sg.Input(key="subject", do_not_clear=False)],
    [sg.Text("category:"), sg.Input(key="category", do_not_clear=False)],
    [sg.Text("prerequisite:"), sg.Input(key="prerequisite", do_not_clear=False)],
    [sg.Text("course_location:"), sg.Input(key="courseLocation", do_not_clear=False)],
    [sg.Text("course_time:"), sg.Input(key="courseTime", do_not_clear=False)],
    [sg.Text("incharge_name:"), sg.Input(key="inchargeName", do_not_clear=False)],
    [sg.Text("incharge:"), sg.Input(key="incharge", do_not_clear=False)],
    [sg.Text("incharge_field:"), sg.Input(key="inchargeField", do_not_clear=False)],
    [sg.Text("office_location:"), sg.Input(key="officeLocation", do_not_clear=False)],
    [sg.Text("incharge_phone:"), sg.Input(key="inchargePhone", do_not_clear=False)],
    [sg.Text("incharge_email:"), sg.Input(key=" inchargeEmail", do_not_clear=False)],
    [sg.Text("teacher_name:"), sg.Input(key="teacherName", do_not_clear=False)],
    [sg.Text("teacher_rank:"), sg.Input(key="teacherRank", do_not_clear=False)],
    [sg.Text("teacher_email:"), sg.Input(key="teacherEmail", do_not_clear=False)],
    [sg.Text("teacher_location:"), sg.Input(key="teacherLocation", do_not_clear=False)],
    [sg.Text("last_update: "), sg.Input(key="lastUpdate", do_not_clear=False)],
    [sg.Text("subject_description:"), sg.Input(key="subjectDescription", do_not_clear=False)],
    [sg.Text("purpose1:"), sg.Input(key="purpose1", do_not_clear=False)],
    [sg.Text("sp1:"), sg.Input(key="sp1", do_not_clear=False)],
    [sg.Text("do1:"), sg.Input(key="do1", do_not_clear=False)],
    [sg.Text("k1:"), sg.Input(key="k1", do_not_clear=False)],
    [sg.Text("a1:"), sg.Input(key="a1", do_not_clear=False)],
    [sg.Text("s1:"), sg.Input(key="s1", do_not_clear=False)],
    [sg.Text("ea1:"), sg.Input(key="ea1", do_not_clear=False)],
    [sg.Text("tm1:"), sg.Input(key="tm1", do_not_clear=False)],
    [sg.Text("lm1:"), sg.Input(key="lm1", do_not_clear=False)],
    [sg.Text("et1:"), sg.Input(key="et1", do_not_clear=False)],
    [sg.Text("em1:"), sg.Input(key="em1", do_not_clear=False)],
    [sg.Text("t1:"), sg.Input(key="t1", do_not_clear=False)],
    [sg.Text("purpose2:"), sg.Input(key="purpose2", do_not_clear=False)],
    [sg.Text("sp2:"), sg.Input(key="sp2", do_not_clear=False)],
    [sg.Text("do2:"), sg.Input(key="do2", do_not_clear=False)],
    [sg.Text("k2:"), sg.Input(key="k2", do_not_clear=False)],
    [sg.Text("a2:"), sg.Input(key="a2", do_not_clear=False)],
    [sg.Text("s2:"), sg.Input(key="s2", do_not_clear=False)],
    [sg.Text("ea2:"), sg.Input(key="ea2", do_not_clear=False)],
    [sg.Text("tm2:"), sg.Input(key="tm2", do_not_clear=False)],
    [sg.Text("lm2:"), sg.Input(key="lm2", do_not_clear=False)],
    [sg.Text("et2:"), sg.Input(key="et2", do_not_clear=False)],
    [sg.Text("em2:"), sg.Input(key="em2", do_not_clear=False)],
    [sg.Text("t2:"), sg.Input(key="t2", do_not_clear=False)],
    [sg.Text("purpose3:"), sg.Input(key="purpose3", do_not_clear=False)],
    [sg.Text("sp3:"), sg.Input(key="sp3", do_not_clear=False)],
    [sg.Text("do3:"), sg.Input(key="do3", do_not_clear=False)],
    [sg.Text("k3:"), sg.Input(key="k3", do_not_clear=False)],
    [sg.Text("a3:"), sg.Input(key="a3", do_not_clear=False)],
    [sg.Text("s3:"), sg.Input(key="s3", do_not_clear=False)],
    [sg.Text("ea3:"), sg.Input(key="ea3", do_not_clear=False)],
    [sg.Text("tm3:"), sg.Input(key="tm3", do_not_clear=False)],
    [sg.Text("lm3:"), sg.Input(key="lm3", do_not_clear=False)],
    [sg.Text("et3:"), sg.Input(key="et3", do_not_clear=False)],
    [sg.Text("em3:"), sg.Input(key="em3", do_not_clear=False)],
    [sg.Text("t3:"), sg.Input(key="t3", do_not_clear=False)],
    [sg.Text("purpose4:"), sg.Input(key="purpose4", do_not_clear=False)],
    [sg.Text("sp4:"), sg.Input(key="sp4", do_not_clear=False)],
    [sg.Text("do4:"), sg.Input(key="do4", do_not_clear=False)],
    [sg.Text("k4:"), sg.Input(key="k4", do_not_clear=False)],
    [sg.Text("a4:"), sg.Input(key="a4", do_not_clear=False)],
    [sg.Text("s4:"), sg.Input(key="s4", do_not_clear=False)],
    [sg.Text("ea4:"), sg.Input(key="ea4", do_not_clear=False)],
    [sg.Text("tm4:"), sg.Input(key="tm4", do_not_clear=False)],
    [sg.Text("lm4:"), sg.Input(key="lm4", do_not_clear=False)],
    [sg.Text("et4:"), sg.Input(key="et4", do_not_clear=False)],
    [sg.Text("em4:"), sg.Input(key="em4", do_not_clear=False)],
    [sg.Text("t4:"), sg.Input(key="t4", do_not_clear=False)],
    [sg.Text("purpose5:"), sg.Input(key="purpose5", do_not_clear=False)],
    [sg.Text("sp5:"), sg.Input(key="sp5", do_not_clear=False)],
    [sg.Text("do5:"), sg.Input(key="do5", do_not_clear=False)],
    [sg.Text("k5:"), sg.Input(key="k5", do_not_clear=False)],
    [sg.Text("a5:"), sg.Input(key="a5", do_not_clear=False)],
    [sg.Text("s5:"), sg.Input(key="s5", do_not_clear=False)],
    [sg.Text("ea5:"), sg.Input(key="ea5", do_not_clear=False)],
    [sg.Text("tm5:"), sg.Input(key="tm5", do_not_clear=False)],
    [sg.Text("lm5:"), sg.Input(key="lm5", do_not_clear=False)],
    [sg.Text("et5:"), sg.Input(key="et5", do_not_clear=False)],
    [sg.Text("em5:"), sg.Input(key="em5", do_not_clear=False)],
    [sg.Text("t5:"), sg.Input(key="t5", do_not_clear=False)],
    [sg.Text("purpose6:"), sg.Input(key="purpose6", do_not_clear=False)],
    [sg.Text("sp6:"), sg.Input(key="sp6", do_not_clear=False)],
    [sg.Text("do6:"), sg.Input(key="do6", do_not_clear=False)],
    [sg.Text("k6:"), sg.Input(key="k6", do_not_clear=False)],
    [sg.Text("a6:"), sg.Input(key="a6", do_not_clear=False)],
    [sg.Text("s6:"), sg.Input(key="s6", do_not_clear=False)],
    [sg.Text("ea6:"), sg.Input(key="ea6", do_not_clear=False)],
    [sg.Text("tm6:"), sg.Input(key="tm6", do_not_clear=False)],
    [sg.Text("lm6:"), sg.Input(key="lm6", do_not_clear=False)],
    [sg.Text("et6:"), sg.Input(key="et6", do_not_clear=False)],
    [sg.Text("em6:"), sg.Input(key="em6", do_not_clear=False)],
    [sg.Text("t6:"), sg.Input(key="t6", do_not_clear=False)],
    [sg.Text("purpose7:"), sg.Input(key="purpose7", do_not_clear=False)],
    [sg.Text("sp7:"), sg.Input(key="sp7", do_not_clear=False)],
    [sg.Text("do7:"), sg.Input(key="do7", do_not_clear=False)],
    [sg.Text("k7:"), sg.Input(key="k7", do_not_clear=False)],
    [sg.Text("a7:"), sg.Input(key="a7", do_not_clear=False)],
    [sg.Text("s7:"), sg.Input(key="s7", do_not_clear=False)],
    [sg.Text("ea7:"), sg.Input(key="ea7", do_not_clear=False)],
    [sg.Text("tm7:"), sg.Input(key="tm7", do_not_clear=False)],
    [sg.Text("lm7:"), sg.Input(key="lm7", do_not_clear=False)],
    [sg.Text("et7:"), sg.Input(key="et7", do_not_clear=False)],
    [sg.Text("em7:"), sg.Input(key="em7", do_not_clear=False)],
    [sg.Text("t7:"), sg.Input(key="t7", do_not_clear=False)],
    [sg.Text("purpose8:"), sg.Input(key="purpose8", do_not_clear=False)],
    [sg.Text("sp8:"), sg.Input(key="sp8", do_not_clear=False)],
    [sg.Text("do8:"), sg.Input(key="do8", do_not_clear=False)],
    [sg.Text("k8:"), sg.Input(key="k8", do_not_clear=False)],
    [sg.Text("a8:"), sg.Input(key="a8", do_not_clear=False)],
    [sg.Text("s8:"), sg.Input(key="s8", do_not_clear=False)],
    [sg.Text("ea8:"), sg.Input(key="ea8", do_not_clear=False)],
    [sg.Text("tm8:"), sg.Input(key="tm8", do_not_clear=False)],
    [sg.Text("lm8:"), sg.Input(key="lm8", do_not_clear=False)],
    [sg.Text("et8:"), sg.Input(key="et8", do_not_clear=False)],
    [sg.Text("em8:"), sg.Input(key="em8", do_not_clear=False)],
    [sg.Text("t8:"), sg.Input(key="t8", do_not_clear=False)],
    [sg.Text("purpose8:"), sg.Input(key="purpose1", do_not_clear=False)],
    [sg.Button("Create Contract"), sg.Exit()],
]

# Wrap your layout in a Scrolled Element
layout = [[sg.Column(layout, scrollable=True, vertical_scroll_only=True, size=(800, 600))]]

window = sg.Window("Contract Generator", layout, element_justification="right")

while True:
    event, inputs = window.read()
    if event == sg.WIN_CLOSED or event == "Exit":
        break
    if event == "Create Contract":
        # Render the template, save new word document & inform user
        doc.render(inputs)
        output_path = Path(__file__).parent / f"contract.docx"
        doc.save(output_path)
        sg.popup("File saved", f"File has been saved here: {output_path}")

window.close()
